Homework #7
vytcus/ageben pull request #10
Opened 2021-06-10 19:22 UTC by agathanelle

2021-06-11 06:12 UTC, vytcus requested changes
All good, tik siūlyčiau panaudoti previous state, kad sužinoti seną dot'ų skaičių.

2021-06-11 06:12 UTC, vytcus commented on eshop/src/common/components/Spinner.jsx
> +    let times = 0;
Šitas cons'tas nereikalingas, nes `setDot` viduje turi priėjimą prie seno state.

2021-06-11 10:28 UTC, agathanelle commented on eshop/src/common/components/Spinner.jsx
> +    let times = 0;
Bandžiau įdėti` if(dot.length>3){setDot("");} `į useEffect, bet pastebėjau su console.log, kad dot visą laiką tuščias useEffect viduje, tai dabar įdėjau už useEffect ribų ir veikia be tų papildomų variables

2021-06-11 10:35 UTC, vytcus requested changes
Liuks, dar tik vieną pakeitimą norėčiau pamatyti

2021-06-11 10:35 UTC, vytcus commented on eshop/src/common/components/Spinner.jsx
> +  if (dot.length > 3) setDot("");
Dot'ų nusetinimą į kažkokį skaičių reiktų suhandlinti vienoje vietoje. Šiuo atveju 8 eilutėje.
Gali panaudoti ternary operator ir if'o nebereiks ;)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

2021-06-12 11:24 UTC, vytcus approved these changes

2021-06-12 19:35 UTC, merged